# Script to build my research page from a list of projects stored in a csv file

with open('./research.md', 'w') as f:
    # First write the markdown header
    f.write("""---
layout: main
title: Research Projects
tagline: Current and completed research projects
---

<!-- DO NOT EDIT THIS FILE! IT IS GENERATED BY build_research.py -->

<p>Projects that I am leading (<span style="background-color: #009900;" class="fa fa-user"></span>)
or otherwise involved in (<span style="background-color: #6ca0e8;" class="fa fa-book"></span>).</p>

<h2>Current Projects</h2>
<section class="container">
    <div class="row">
""")

    # Now read the CSV file to generate information about each project
    with open('./_research.csv', 'r') as csvf:
        for i, line in enumerate(csvf):
            if i<2: # Ignore the header line and comment line
                continue
            if line.strip() == "__PREVIOUS__":
                # Now switch to previous projects
                f.write("""
    </div>
</section>
<h2>Completed Projects</h2>
<section class="container">
    <div class="row">\n""")
                continue

            l = line.strip().split(',,') # Split on double-comas
            short_title = l[0].strip()
            long_title = l[1].strip()
            url = l[2].strip()
            desc = l[3].strip()
            colour = l[4].strip()
            icon = l[5].strip()
            img = l[6].strip() if len(l)>6 else ""
            
            s = """
    <div class="6u">
        <ul class="style">
            <li>
                <a href="{url}"><span style="background-color: #{colour};" class="fa {icon}"></span></a>
                <h3><a href="{url}">{short_title}</a></h3>
                {long_title}
            </li>
            <li style="font-size: small; line-height: 20px;">{desc}</li>
            <li>&nbsp;</li>
        </ul>
    </div>"""
            f.write(s.format(short_title= short_title, long_title=long_title, url=url, desc=desc, colour=colour, icon=icon))

        # Finish by closing the html
    f.write("""
    </div>
</section>""")
